Added a catch for a missing username

diff --git a/Steamy_Cats b/Steamy_Cats
--- a/Steamy_Cats
+++ b/Steamy_Cats
@@ -604,7 +604,17 @@ then
 fi
 
 WHICHACC=$(echo "$NAMES" | sed -n "$WHICHSTEAM"p)
-WEBACCNUM=$(grep -FB3 "$WHICHACC" ~/.steam/steam/config/loginusers.vdf | head -n1 | cut -d\" -f2)
+
+# We should check to see if the username can be found in users
+# If the name has been changed and no Steam restart, had an error
+if grep -qFB3 "$WHICHACC" ~/.steam/steam/config/loginusers.vdf
+then
+	WEBACCNUM=$(grep -FB3 "$WHICHACC" ~/.steam/steam/config/loginusers.vdf | head -n1 | cut -d\" -f2)
+else
+	echo "We can't find your username, try restarting Steam"
+	echo "This can happen if you changed your username without restarting Steam"
+	exit 1
+fi
 
 echo "We are using: $WHICHACC :: $WEBACCNUM"
 
