Improved Linux Native Detection More aggressive exit Added some more safety on some greps Added a notification about missing games

diff --git a/Steamy_Cats b/Steamy_Cats
--- a/Steamy_Cats
+++ b/Steamy_Cats
@@ -7,7 +7,7 @@ this_command="false"
 previous_command="false"
 trap 'previous_command=$this_command; this_command=$BASH_COMMAND' DEBUG
 trap 'rm -rf "/var/tmp/Steamy_Cats/"' EXIT
-trap 'echo "Exit Code: $? ~~ Last Command: $previous_command"' ERR
+trap '(echo "Exit Code: $? ~~ Last Command: $previous_command" ; exit 1)' ERR
 
 rm -rf /var/tmp/Steamy_Cats/
 mkdir -p /var/tmp/Steamy_Cats/ /var/tmp/Steamy_Cats/fragments/ /var/tmp/Steamy_Cats/rewrites/
@@ -116,7 +116,7 @@ function parse_config()
     else
       # We are removing categories we create here
       APPS_SECTION=$(head -n "$END_APPS" "$1" | tail -$COUNT_LINES |\
-        grep -v -e '"TAGS ' -e '"SFLAGS ' -e '"APP ' -e '"ALL"' -e '"PDB ' -e '"RELEASE ' -e '"REVIEW ')
+        grep -v -e '"TAGS ' -e '"SFLAGS ' -e '"APP ' -e '"PDB ' -e '"RELEASE ' -e '"REVIEW ')
     fi
 
     # List of game IDs
@@ -297,7 +297,7 @@ function make_categories()
   {
     # Write if we are Linux native
     # Else check Proton DB ratings
-    if grep -q "^$1$" /var/tmp/Steamy_Cats/Linux
+    if grep -q "^$1$" /var/tmp/Steamy_Cats/Linux || grep -q "^$1$" /var/tmp/Steamy_Cats/Linux2
     then
       printf "\t\t\t\t\t\t\t\"%s\"\t\t\"APP NATIVE LINUX\"\n" "301" >> /var/tmp/Steamy_Cats/fragments/"$1"
     else
@@ -331,45 +331,55 @@ function make_categories()
   {
     if [ -f "$HOME/.local/share/steam_store_frontend/$1.html" ] \
       || ! grep -q '~FAILED~' "$HOME/.local/share/steam_store_frontend/$1.html"
-  then
-    maketags "$1"
-    makeflags "$1"
-    tagnative "$1"
-    makerelease "$1"
-    makereviews "$1"
-  else
-    echo "~FAILED~" > "$HOME/.local/share/steam_store_frontend/$1.html"
-    printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "200" "STORE MISSING" >> /var/tmp/Steamy_Cats/fragments/"$1"
-    write_proton_db_scores "$1"
-  fi
+    then
+      maketags "$1"
+      makeflags "$1"
+      tagnative "$1"
+      makerelease "$1"
+      makereviews "$1"
+    else
+      echo "~FAILED~" > "$HOME/.local/share/steam_store_frontend/$1.html"
+      printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "200" "STORE MISSING" >> /var/tmp/Steamy_Cats/fragments/"$1"
+      write_proton_db_scores "$1"
+    fi
 
-  # Write the all group and final bracket
-  {
-    printf "\t\t\t\t\t\t\t\"%s\"\t\t\"ALL\"\n" "330"
-    printf "\t\t\t\t\t\t}\n"
-  } >> /var/tmp/Steamy_Cats/fragments/"$1"
+    # Write the all group and final bracket
+    if grep -q '"ALL"' /var/tmp/Steamy_Cats/fragments/"$1"
+    then
+      printf "\t\t\t\t\t\t}\n" >> /var/tmp/Steamy_Cats/fragments/"$1"
+    else
+      {
+        printf "\t\t\t\t\t\t\t\"%s\"\t\t\"ALL\"\n" "330"
+        printf "\t\t\t\t\t\t}\n"
+      } >> /var/tmp/Steamy_Cats/fragments/"$1"
+    fi
 
 
-  # Fixing our handling of the Hidden field
-  if grep -q $'\t\t\t\t\t"Hidden"\t\t"' /var/tmp/Steamy_Cats/fragments/"$1"
-  then
-    HIDDENLINE=$(grep $'\t\t\t\t\t"Hidden"' /var/tmp/Steamy_Cats/fragments/"$1")
-    grep -hv $'\t\t\t\t\t"Hidden"' /var/tmp/Steamy_Cats/fragments/"$1" > /var/tmp/Steamy_Cats/rewrites/"$1"
-    cp /var/tmp/Steamy_Cats/rewrites/"$1" /var/tmp/Steamy_Cats/fragments/"$1"
-    echo "$HIDDENLINE" >> /var/tmp/Steamy_Cats/fragments/"$1"
-  fi
+    # Fixing our handling of the Hidden field
+    if grep -q $'\t\t\t\t\t"Hidden"\t\t"' /var/tmp/Steamy_Cats/fragments/"$1"
+    then
+      HIDDENLINE=$(grep $'\t\t\t\t\t"Hidden"' /var/tmp/Steamy_Cats/fragments/"$1")
+      grep -hv $'\t\t\t\t\t"Hidden"' /var/tmp/Steamy_Cats/fragments/"$1" > /var/tmp/Steamy_Cats/rewrites/"$1"
+      cp /var/tmp/Steamy_Cats/rewrites/"$1" /var/tmp/Steamy_Cats/fragments/"$1"
+      echo "$HIDDENLINE" >> /var/tmp/Steamy_Cats/fragments/"$1"
+    fi
 
-  printf "\t\t\t\t\t}\n" >> /var/tmp/Steamy_Cats/fragments/"$1"
-}
+    printf "\t\t\t\t\t}\n" >> /var/tmp/Steamy_Cats/fragments/"$1"
+  }
 
 # Main entry logic just calls function above a bunch
 echo "Adding new category tags to the games!"
 
 # Prepare the release year, Linux native, and review information for parsing
 cd "$HOME"/.local/share/steam_store_frontend/ || (echo "Downloads location does not exist, can't parse" ; exit 1)
-grep "<b>Release Date:" -- * | sed -nr 's/([0-9]*\.).*([0-9]{4}).*/\1\2/p' > /var/tmp/Steamy_Cats/Release_Year
-grep -l 'data-os="linux">' -- * | cut -d. -f1 > /var/tmp/Steamy_Cats/Linux
-grep -A1 "Overall Reviews:" -- * | grep "game_review_summary" | grep -v "Need more user reviews" | sed 's/\..*\">/~/' | cut -d\< -f1 > /var/tmp/Steamy_Cats/Reviews
+grep -H "<b>Release Date:" -- * | sed -nr 's/([0-9]*\.).*([0-9]{4}).*/\1\2/p' > /var/tmp/Steamy_Cats/Release_Year
+grep -Hl 'data-os="linux">' -- * | cut -d. -f1 > /var/tmp/Steamy_Cats/Linux
+while read -r filen
+do
+  grep -H '<div class="game_area_purchase_platform">' "$filen" | head -n 1 |\
+    grep '<span class="platform_img linux">' | cut -d. -f2 | cut -d/ -f2 >> /var/tmp/Steamy_Cats/Linux2
+done <<< "$(find .)"
+grep -HA1 "Overall Reviews:" -- * | grep "game_review_summary" | grep -v "Need more user reviews" | sed 's/\..*\">/~/' | cut -d\< -f1 > /var/tmp/Steamy_Cats/Reviews
 
 cd /var/tmp/Steamy_Cats/fragments/ || (echo "Our fragment location is missing" ; exit 1)
 for i in *
@@ -537,6 +547,7 @@ function check_valid
       PDB_PLAT="$(grep PDB\ MODE\ Platinum /var/tmp/newconfig.vdf | sort -n | uniq -c | awk '{print  $1}')"
       NATIVECOUNT="$(grep APP\ NATIVE\ LINUX /var/tmp/newconfig.vdf | sort -n | uniq -c | awk '{print  $1}')"
       echo "PDB Platinum Ratings: $PDB_PLAT :: Native Games: $NATIVECOUNT"
+      echo "Any missing games should be added to a group, such as ALL, and then the script rerun"
       echo "Old config backed up to /var/tmp/oldconfig.vdf"
       echo "New config written. To apply, run the below command:"
       echo "cp /var/tmp/newconfig.vdf $OUR_CONFIG"
