Initial checkin, flags not working

diff --git a/Steamy_Cats b/Steamy_Cats
--- a/Steamy_Cats
+++ b/Steamy_Cats
@@ -104,7 +104,6 @@ function download_store()
 {
 	function cleandls
 	{
-		find "$DLOC" -size -27c -type f -delete
 		# Deleting failed downloads to try again
 		cd "$DLOC" || exit 1
 		if grep -q '>Error<' -- *
@@ -123,29 +122,19 @@ function download_store()
 		# This is set through a CLI switch
 		if [ "$CLEAN_DLS" == "true" ]
 		then
-			if grep -q -e '~FAILED~' -e '"success":false}' -- *
+			if grep -q '~FAILED~' -- *
 			then
-				grep -Zl -e '~FAILED~' -e '"success":false}' -- * | xargs --null rm
+				grep -Zl '~FAILED~' -- * | xargs --null rm
 			fi
+
+			# Corrupt downloads
+			find "$DLOC" -size -27c -type f -delete
 			find "$DLOC" -empty -type f -delete
 		fi
 	}
 
-	if [ "$1" == "--front" ]
-	then
-		EXITMESSAGE="Steam Store User Readable Page"
-		DLOC="$HOME/.local/share/steam_store_frontend/"
-		TLOC="https://store.steampowered.com/app/"
-	elif [ "$1" == "--api" ]
-	then
-		EXITMESSAGE="Steam Store API"
-		TLOC="https://store.steampowered.com/api/appdetails/?appids="
-		DLOC="$HOME/.local/share/steam_store_api_json/"
-	else
-		echo "This function takes one argument."
-		echo "Supply --front for frontend download or --api for API"
-		exit
-	fi
+	DLOC="$HOME/.local/share/steam_store_frontend/"
+	TLOC="https://store.steampowered.com/app/"
 
 	mkdir -p "$DLOC"
 	cleandls
@@ -167,7 +156,7 @@ function download_store()
 		fi
 	done
 
-	if [ "$(wc -w <<< "$DL_LIST")" -gt 50 ]
+	if [ "$(wc -w <<< "$DL_LIST")" -gt 25 ]
 	then
 		echo "Downloading $(wc -w <<< "$DL_LIST") files" && echo
 	else
@@ -191,23 +180,6 @@ function download_store()
 			sleep 1
 		fi
 
-		let LONG_SLEEP=$DOWNLOADED%200
-		if [[ $LONG_SLEEP -eq 0 ]] && [ "$1" == "--api" ]
-		then
-			let DL_COUNT=$DOWNLOADED-1
-			tput cuu 1 && tput el # Using this to overwrite previous line
-			echo "5 MINUTE SLEEP (DL RATE LIMIT) $DL_COUNT downloads started of $DOWNLOADING total" && echo
-			wait
-			for y in $(seq 300)
-			do
-				tput cuu 1 && tput el # Using this to overwrite previous line
-				echo "Sleeping $y seconds of 300 (DL RATE LIMIT)"
-				sleep 1
-			done
-			# Clearing the line above
-			tput cuu 1 && tput el # Using this to overwrite previous line
-		fi
-
 		curl -L --cookie "mature_content=1 ; birthtime=-729000000" -s -o "$DLOC""$i".html "$TLOC$i" &
 		tput cuu 1 && tput el # Using this to overwrite previous line
 		echo "$DOWNLOADED downloads started of $DOWNLOADING total"
@@ -217,18 +189,12 @@ function download_store()
 
 	cleandls
 
-	# Parse the Store API Downloads for information for later
-	if [ "$1" == "--api" ]
-	then
-		# Some entries have no release date
-		cat -- * | jq -j 'keys[] as $k | "\($k)~\(.[].data.release_date.date[-4:])\n"' > /var/tmp/Steamy_Cats/Release_Year
-		cat -- * | jq -r 'keys[] as $k | $k + "~" + .[].data.categories[]?.description' > /var/tmp/Steamy_Cats/Flags
-	elif [ "$1" == "--front" ]
-	then
-		grep -A1 "Overall Reviews:" -- * | grep "game_review_summary" | grep -v "Need more user reviews" | sed 's/\..*\">/~/' | cut -d\< -f1 > /var/tmp/Steamy_Cats/Reviews
-	fi
+	# Parse this information here, so we have an easy search later
+	grep "<b>Release Date:" -- * | sed -nr 's/([0-9]*\.).*([0-9]{4}).*/\1\2/p' > /var/tmp/Steamy_Cats/Release_Year
+	grep -l 'data-os="linux">' -- * | cut -d. -f1 > /var/tmp/Steamy_Cats/Linux
+	grep -A1 "Overall Reviews:" -- * | grep "game_review_summary" | grep -v "Need more user reviews" | sed 's/\..*\">/~/' | cut -d\< -f1 > /var/tmp/Steamy_Cats/Reviews
 
-	echo "Downloads complete for the $EXITMESSAGE."
+	echo "Downloads complete for the Store Frontend."
 }
 
 #######################################################################################
@@ -239,19 +205,18 @@ function make_categories()
 {
 	function makeflags
 	{
-		if ! grep -q "^$1~" /var/tmp/Steamy_Cats/Flags
+		if ! grep -q "^$1~" "$HOME/.local/share/steam_store_frontend/$1.html" | grep -q 'class="name"[^\>]*\>[^\<]*'
 		then
 			printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "100" "SFLAGS NONE" >> /var/tmp/Steamy_Cats/fragments/"$1"
 			return
 		fi
 
-		FLAGS="$(grep "^$1~" /var/tmp/Steamy_Cats/Flags | cut -d~ -f2)"
 		VALNUM=100
 		while read -r line
 		do
 			printf "\t\t\t\t\t\t\t\"%s\"\t\t\"SFLAGS %s\"\n" "$VALNUM" "$line" >> /var/tmp/Steamy_Cats/fragments/"$1"
 			let VALNUM=$VALNUM+1
-		done <<< "$FLAGS"
+		done <<< "$(grep game_area_details_specs "$HOME/.local/share/steam_store_frontend/$1.html" | grep -o 'class="name"[^\>]*\>[^\<]*' | cut -d\> -f2)"
 	}
 
 	function maketags
@@ -281,7 +246,7 @@ function make_categories()
 	{
 		# Write if we are Linux native
 		# Else check Proton DB ratings
-		if grep -q '"linux":true' "$HOME/.local/share/steam_store_api_json/$1.html"
+		if grep -q "^$1~" /var/tmp/Steamy_Cats/Linux
 		then
 			printf "\t\t\t\t\t\t\t\"%s\"\t\t\"APP NATIVE LINUX\"\n" "301" >> /var/tmp/Steamy_Cats/fragments/"$1"
 		else
@@ -291,17 +256,12 @@ function make_categories()
 
 	function makerelease
 	{
-		if ! grep -q "^$1~" /var/tmp/Steamy_Cats/Release_Year
+		if ! grep -q "^$1\." /var/tmp/Steamy_Cats/Release_Year
 		then
 			printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "340" "RELEASE UNKNOWN" >> /var/tmp/Steamy_Cats/fragments/"$1"
 		else
-			RELYEAR="$(grep "^$1~" /var/tmp/Steamy_Cats/Release_Year | cut -d~ -f2)"
-			if [ "$RELYEAR" == "null" ]
-			then
-				printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "340" "RELEASE UNKNOWN" >> /var/tmp/Steamy_Cats/fragments/"$1"
-			else
-				printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "340" "RELEASE $RELYEAR" >> /var/tmp/Steamy_Cats/fragments/"$1"
-			fi
+			RELYEAR="$(grep "^$1\." /var/tmp/Steamy_Cats/Release_Year | cut -d. -f2)"
+			printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "340" "RELEASE $RELYEAR" >> /var/tmp/Steamy_Cats/fragments/"$1"
 		fi
 	}
 
@@ -318,24 +278,18 @@ function make_categories()
 
 	function makecats
 	{
-		if [ -f "$HOME/.local/share/steam_store_api_json/$1.html" ]
+		if [ -f "$HOME/.local/share/steam_store_frontend/$1.html" ] \
+			|| grep -q '~FAILED~' "$HOME/.local/share/steam_store_frontend/$1.html"
 		then
+			maketags "$1"
 			makeflags "$1"
 			tagnative "$1"
 			makerelease "$1"
-		else
-			printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "100" "SFLAGS NONE" >> /var/tmp/Steamy_Cats/fragments/"$1"
-			printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "101" "RELEASE UNKNOWN" >> /var/tmp/Steamy_Cats/fragments/"$1"
-			write_proton_db_scores "$1"
-		fi
-
-		if [ -f "$HOME/.local/share/steam_store_frontend/$1.html" ]
-		then
-			maketags "$1"
 			makereviews "$1"
 		else
 			echo "~FAILED~" > "$HOME/.local/share/steam_store_frontend/$1.html"
-			printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "200" "TAGS NONE" >> /var/tmp/Steamy_Cats/fragments/"$1"
+			printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "200" "STORE MISSING" >> /var/tmp/Steamy_Cats/fragments/"$1"
+			write_proton_db_scores "$1"
 		fi
 		
 		# Write the all group and final bracket
@@ -673,8 +627,7 @@ then
 fi
 
 parse_config "$OUR_CONFIG" || exit
-download_store --front
-download_store --api
+download_store
 download_proton_db
 make_categories "$OUR_CONFIG"
 assemble_steam_config "$OUR_CONFIG"
