We now calculate the mean PDB score

diff --git a/Steamy_Cats b/Steamy_Cats
--- a/Steamy_Cats
+++ b/Steamy_Cats
@@ -39,7 +39,8 @@ function parse_config()
 
 	echo "Begin processing $COUNT_LINES lines of configuration in $1"
 
-	APPS_SECTION=$(head -n "$END_APPS" "$1" | tail -$COUNT_LINES | grep -v -e '"TAGS ' -e '"FLAGS ' -e '"APP ' -e '"ALL"')
+	# This is an important part, it removes our old config and is the variable we process
+	APPS_SECTION=$(head -n "$END_APPS" "$1" | tail -$COUNT_LINES | grep -v -e '"TAGS ' -e '"SFLAGS ' -e '"APP ' -e '"ALL"' -e '"PDB ')
 	GAMES=$(echo "$APPS_SECTION" | grep $'^\t\t\t\t\t\"' | cut -d\" -f2)
 
 	function copyexisting
@@ -168,9 +169,9 @@ function make_categories()
 		do
 			if [ "$line" == "" ]
 			then
-				printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "$VALNUM" "FLAGS NONE" >> /var/tmp/steamy_cats/"$1"
+				printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "$VALNUM" "SFLAGS NONE" >> /var/tmp/steamy_cats/"$1"
 			else
-				printf "\t\t\t\t\t\t\t\"%s\"\t\t\"FLAGS %s\"\n" "$VALNUM" "$line" >> /var/tmp/steamy_cats/"$1"
+				printf "\t\t\t\t\t\t\t\"%s\"\t\t\"SFLAGS %s\"\n" "$VALNUM" "$line" >> /var/tmp/steamy_cats/"$1"
 			fi
 			let VALNUM=$VALNUM+1
 		done
@@ -179,7 +180,7 @@ function make_categories()
 		then
 			if grep -q "You must login to see this content." "$HOME/.local/share/steam_store_frontend/$1.html"
 			then
-				printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "320" "FLAGS ADULT" >> /var/tmp/steamy_cats/"$1"
+				printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "320" "SFLAGS ADULT" >> /var/tmp/steamy_cats/"$1"
 			fi
 
 			# This is basically the same as the flags above, but making it a function complicates things a bit IMO
@@ -260,15 +261,71 @@ function download_proton_db()
 
 function write_proton_db_scores()
 {
-	let PDBNUM=301
+	# Mode
 	PDB_MODE="$(grep "^$1" /var/tmp/steamy_pdb | sort | uniq -c | sort -nr | head -n1 | cut -d, -f2)"
 	if [ "$PDB_MODE" == "" ]
 	then
-		printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB UNRATED\"\n" "$PDBNUM" >> /var/tmp/steamy_cats/"$1"
+		printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB UNRATED\"\n" "301" >> /var/tmp/steamy_cats/"$1"
 		return
 	else
-		printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB MODE %s\"\n" "$PDBNUM" "$PDB_MODE" >> /var/tmp/steamy_cats/"$1"
+		printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB MODE %s\"\n" "301" "$PDB_MODE" >> /var/tmp/steamy_cats/"$1"
+		let PDBNUM=$PDBNUM+1
 	fi
+
+	# Mean
+	let TOTAL=0
+	let NUMVALS=0
+	while read -r line
+	do
+		let MULT1="$(echo "$line" | awk '{print $1}')"
+		let NUMVALS=$NUMVALS+$MULT1
+		case "$(echo "$line" | cut -d, -f2)" in
+			"Platinum")
+				let MULT2=4
+				;;
+			"Gold")
+				let MULT2=3
+				;;
+			"Silver")
+				let MULT2=2
+				;;
+			"Bronze")
+				let MULT2=1
+				;;
+			"Borked")
+				let MULT2=0
+				;;
+			*)
+				echo "We shouldn't reach here"
+				exit 1
+				;;
+		esac
+
+		let TOTAL=$TOTAL+$MULT1*$MULT2
+	done <<< "$(grep "^$1" /var/tmp/steamy_pdb | sort | uniq -c)"
+	let RAWMEAN=$TOTAL/$NUMVALS
+	let ROUNDMEAN=$(echo $RAWMEAN | awk '{print int($1+0.5)}')
+	case $ROUNDMEAN in
+		4)
+			printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB MEAN Platinum\"\n" "302" >> /var/tmp/steamy_cats/"$1"
+			;;
+		3)
+			printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB MEAN Gold\"\n" "302" >> /var/tmp/steamy_cats/"$1"
+			;;
+		2)
+			printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB MEAN Silver\"\n" "302" >> /var/tmp/steamy_cats/"$1"
+			;;
+		1)
+			printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB MEAN Bronze\"\n" "302" >> /var/tmp/steamy_cats/"$1"
+			;;
+		0)
+			printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB MEAN Borked\"\n" "302" >> /var/tmp/steamy_cats/"$1"
+			;;
+		*)
+			echo "Somehow our math failed"
+			exit 1
+			;;
+	esac
 }
 
 #######################################################################################
