Made PDB calcs not suck

diff --git a/Steamy_Cats b/Steamy_Cats
--- a/Steamy_Cats
+++ b/Steamy_Cats
@@ -58,7 +58,7 @@ parse_config() {
 
     # Find the JSON containing our games, then extract the APP ID with JQ
     GAMESLIST="$(grep "var rgGames" /var/tmp/Steamy_Cats/Community_Profile | \
-      sed -e 's/var rgGames \= \[//' -e 's/\]\;//' -e 's/\,[{]/\n\{/g' | jq '.appid' | grep '[0-9]*')"
+      sed -e 's/var rgGames \= \[//' -e 's/\]\;//' -e 's/\,[{]/\n\{/g' | jq '.appid' | grep '[0-9]')"
     if [ "$GAMESLIST" == "" ]
     then
       tput bold
@@ -272,6 +272,7 @@ download_store() {
 
 make_categories() {
   local VALNUM TAGS HIDDENLINE i line which_game rel_year rev_score
+
   makeflags() {
     if ! grep "game_area_details_specs" "$HOME/.local/share/steam_store_frontend/$1.html" | grep -q 'class="name"'
     then
@@ -309,31 +310,19 @@ make_categories() {
     done <<< "$TAGS"
   }
 
-  tagnative() {
-    # Write if we are Linux native
-    # Else check Proton DB ratings
-    if grep -q -e "^$1$" -e "\"$1\"" /var/tmp/Steamy_Cats/Linux /var/tmp/Steamy_Cats/Linux2 "$HOME"/.local/share/SteamLinux.json
-    then
-      printf "\t\t\t\t\t\t\t\"%s\"\t\t\"APP NATIVE LINUX\"\n" "301" >> /var/tmp/Steamy_Cats/fragments/"$1"
-    else
-      write_proton_db_scores "$1"
-    fi
-  }
-
   makecats() {
     if [ -f "$HOME/.local/share/steam_store_frontend/$1.html" ] \
       || ! grep -q '~FAILED~' "$HOME/.local/share/steam_store_frontend/$1.html"
     then
       maketags "$1"
       makeflags "$1"
-      tagnative "$1"
     else
       echo "~FAILED~" > "$HOME/.local/share/steam_store_frontend/$1.html"
       printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "200" "STORE MISSING" >> /var/tmp/Steamy_Cats/fragments/"$1"
       write_proton_db_scores "$1"
     fi
 
-    # Write the all group and final bracket
+    # Write the all group and tags bracket
     if grep -q '"ALL"' /var/tmp/Steamy_Cats/fragments/"$1"
     then
       printf "\t\t\t\t\t\t}\n" >> /var/tmp/Steamy_Cats/fragments/"$1"
@@ -354,30 +343,52 @@ make_categories() {
       echo "$HIDDENLINE" >> /var/tmp/Steamy_Cats/fragments/"$1"
     fi
 
+    # Writing the closing bracket for the game id
     printf "\t\t\t\t\t}\n" >> /var/tmp/Steamy_Cats/fragments/"$1"
   }
 
   echo "Adding new category tags to the games!"
 
+  # Linux Native List Preparation
+  # We check three ways, since the labeling here sucks
   cd "$HOME"/.local/share/steam_store_frontend/ || (echo "Downloads location does not exist, can't parse" ; exit 1)
-
-  # Get files ready to know if we are Linux native
-  # We do three methods, since the labeling here sucks
   grep -Hl 'data-os="linux">' -- * | cut -d. -f1 > /var/tmp/Steamy_Cats/Linux
   grep -m1 -H '<div class="game_area_purchase_platform">' -- * |\
-    grep '<span class="platform_img linux">' | cut -d. -f1 >> /var/tmp/Steamy_Cats/Linux2
-  curl -s -o "$HOME"/.local/share/SteamLinux.json https://raw.githubusercontent.com/SteamDatabase/SteamLinux/master/GAMES.json
+    grep '<span class="platform_img linux">' | cut -d. -f1 >> /var/tmp/Steamy_Cats/Linux
+  curl -s https://raw.githubusercontent.com/SteamDatabase/SteamLinux/master/GAMES.json |\
+    cut -d\" -f2 "$HOME"/.local/share/SteamLinux.json | grep '[0-9]' >> /var/tmp/Steamy_Cats/Linux
+
+  # Linux Native
+  while read -r which_game ; do
+    if [ -f /var/tmp/Steamy_Cats/fragments/"$which_game" ] ; then
+      printf "\t\t\t\t\t\t\t\"%s\"\t\t\"APP NATIVE LINUX\"\n" "301" >> /var/tmp/Steamy_Cats/fragments/"$which_game"
+    fi
+  done <<< "$(sort -u /var/tmp/Steamy_Cats/Linux)"
+
+  my_exact_date
+  # Proton DB Scores
+  while read -r which_game ; do
+    if [ "$SEQUENTIAL" == "true" ] ; then
+      write_proton_db_scores "$which_game" || (echo "ProtonDB score failed" ; exit 1)
+    else
+      write_proton_db_scores "$which_game" || (echo "ProtonDB score failed" ; exit 1) &
+    fi
+  done <<< "$(cd /var/tmp/Steamy_Cats/fragments/ && grep -L LINUX -- *)"
+  wait
+  my_exact_date
 
   # Release date
-  while IFS="." read -r which_game rel_year
-  do
-    printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "340" "RELEASE $rel_year" >> /var/tmp/Steamy_Cats/fragments/"$which_game"
+  while IFS="." read -r which_game rel_year ; do
+    if [ -f /var/tmp/Steamy_Cats/fragments/"$which_game" ] ; then
+      printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "340" "RELEASE $rel_year" >> /var/tmp/Steamy_Cats/fragments/"$which_game"
+    fi
   done <<< "$(grep -H "<b>Release Date:" -- * | sed -nr 's/([0-9]*\.).*([0-9]{4}).*/\1\2/p')"
 
   # Reviews
-  while IFS="~" read -r which_game rev_score
-  do
-    printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "340" "REVIEW $rev_score" >> /var/tmp/Steamy_Cats/fragments/"$which_game"
+  while IFS="~" read -r which_game rev_score ; do
+    if [ -f /var/tmp/Steamy_Cats/fragments/"$which_game" ] ; then
+      printf "\t\t\t\t\t\t\t\"%s\"\t\t\"%s\"\n" "350" "REVIEW $rev_score" >> /var/tmp/Steamy_Cats/fragments/"$which_game"
+    fi
   done <<< "$(grep -HA1 "Overall Reviews:" -- * | grep "game_review_summary" | grep -v "Need more user reviews" | sed 's/\..*\">/~/' | cut -d\< -f1)"
 
   cd /var/tmp/Steamy_Cats/fragments/ || (echo "Our fragment location is missing" ; exit 1)
@@ -433,77 +444,30 @@ download_proton_db() {
   TAR_FILENAME=$(find . | grep "$YEAR" | grep "$MONTH")
   echo "Most recent ProtonDB file appears to be: $TAR_FILENAME"
   tar -zxvf "$TAR_FILENAME" > /dev/null || (echo "Untarring the ProtonDB failed somehow" ; exit 1)
-  jq -r '.[] | [.appId, .rating] | join(",")' "$PDBLOC"/reports/reports_piiremoved.json > /var/tmp/Steamy_Cats/PDB.json
+  jq -r '.[] | [.appId, .rating] | join(",")' "$PDBLOC"/reports/reports_piiremoved.json > /var/tmp/Steamy_Cats/PDB.csv
 }
 
 write_proton_db_scores() {
-  local PDBNUM=0 TOTAL=0 NUMVALS=0 \
-    MULT1 MULT2 RAWMEAN ROUNDMEAN line
-  
+  local pdb_mean pdb_mode
+
   # Mode
-  if ! grep -q "^$1," /var/tmp/Steamy_Cats/PDB.json
+  if ! grep -q "^$1," /var/tmp/Steamy_Cats/PDB.csv
   then
     printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB UNRATED\"\n" "301" >> /var/tmp/Steamy_Cats/fragments/"$1"
     return
   else
-    PDB_MODE="$(grep "^$1," /var/tmp/Steamy_Cats/PDB.json | sort | uniq -c | sort -nr | head -n1 | cut -d, -f2)"
-    printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB MODE %s\"\n" "301" "$PDB_MODE" >> /var/tmp/Steamy_Cats/fragments/"$1"
-    let PDBNUM=$PDBNUM+1
+    pdb_mode="$(grep "^$1," /var/tmp/Steamy_Cats/PDB.csv | sort | uniq -c | sort -nr | head -n1 | cut -d, -f2)"
+    printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB MODE %s\"\n" "301" "$pdb_mode" >> /var/tmp/Steamy_Cats/fragments/"$1"
   fi
 
   # Mean
-  while read -r line
-  do
-    MULT1="$(awk '{print $1}' <<< "$line")"
-    case "$(cut -d, -f2 <<< "$line")" in
-      "Platinum")
-        MULT2=4
-        ;;
-      "Gold")
-        MULT2=3
-        ;;
-      "Silver")
-        MULT2=2
-        ;;
-      "Bronze")
-        MULT2=1
-        ;;
-      "Borked")
-        MULT2=0
-        ;;
-      *)
-        # We set this so we don't have blank reviews counted as borked
-        MULT1=0
-        MULT2="0"
-        ;;
-    esac
-
-    let NUMVALS=$NUMVALS+$MULT1
-    TOTAL=$(( TOTAL+MULT1*MULT2 ))
-  done <<< "$(grep "^$1," /var/tmp/Steamy_Cats/PDB.json | sort | uniq -c)"
-  RAWMEAN=$(( TOTAL/NUMVALS ))
-  ROUNDMEAN=$(awk '{print int($1+0.5)}' <<< "$RAWMEAN")
-  case $ROUNDMEAN in
-    4)
-      printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB MEAN Platinum\"\n" "302" >> /var/tmp/Steamy_Cats/fragments/"$1"
-      ;;
-    3)
-      printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB MEAN Gold\"\n" "302" >> /var/tmp/Steamy_Cats/fragments/"$1"
-      ;;
-    2)
-      printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB MEAN Silver\"\n" "302" >> /var/tmp/Steamy_Cats/fragments/"$1"
-      ;;
-    1)
-      printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB MEAN Bronze\"\n" "302" >> /var/tmp/Steamy_Cats/fragments/"$1"
-      ;;
-    0)
-      printf "\t\t\t\t\t\t\t\"%s\"\t\t\"PDB MEAN Borked\"\n" "302" >> /var/tmp/Steamy_Cats/fragments/"$1"
-      ;;
-    *)
-      echo "Somehow our math failed for ProtonDB"
-      exit 1
-      ;;
-  esac
+  # I have a feeling this whole thing can be done in awk, so that is a todo
+  pdb_mean="$(grep "^$1," /var/tmp/Steamy_Cats/PDB.csv |\
+    sed -e 's/Platinum/4/' -e 's/Gold/3/' -e 's/Silver/2/' -e 's/Bronze/1/' -e 's/Borked/0/' |\
+    awk -F "," '{n++;sum+=$2} END {print n? int((sum/n)+.5) :"Error"}' |\
+    sed -e 's/4/Platinum/' -e 's/3/Gold/' -e 's/2/Silver/' -e 's/1/Bronze/' -e 's/0/Borked/'
+  )"
+  printf "\t\t\t\t\t\t\t\"302\"\t\t\"PDB MEAN %s\"\n" "$pdb_mean" >> /var/tmp/Steamy_Cats/fragments/"$1"
 }
 
 #######################################################################################
